### ISSUE TITLE
HumanNPC#setName errors

### ISSUE THREAD

**Issue by ghost** [TechzoneMC/NPCLib#13]
Anytime I attempt to call setName, it errors out with this error. I've made sure none of the names or anything are null and can show the code if you would like. 

``` Java
java.lang.NullPointerException
        at net.techcable.npclib.nms.NMSLivingNPC.setName(NMSLivingNPC.java:29) ~[?:?]
        at com.reactivemc.hub.listeners.NPCListener.spawnNPC(NPCListener.java:55) ~[?:?]
```

I'm running Spigot 1.7/1.8 protocal hack on the latest version of NPCLib.

**Comment by Techcable** [comment]
Are you on the 2.0 version?

**Comment by ghost** [comment]
Yes I am. I'm on the latest version from the repo.

**Comment by Techcable** [comment]
Please try again with [Build 26](http://ci.techcable.net/job/NPCLib-2.0/26/)
