### ISSUE TITLE
Skins Not Working

### ISSUE THREAD

**Issue by tavonkelly** [TechzoneMC/NPCLib#15]
The server is in online mode and real players who log in get their skins.

Using NPCLib version 2.0.0-beta2-SNAPSHOT

Using this Spigot version:
![Spigot version](http://i.teg.pw/frlk4.png)

Code used to spawn NPC: (almost identical to example provided)

``` java
NPCRegistry registry = NPCLib.getNPCRegistry("awesome-registry", instance);
HumanNPC npc = registry.createHumanNPC("jack");
npc.setName("greeter");
npc.setProtected(true); //Makes invincible
npc.setSkin(UUID.fromString("613517d7-31bb-47bd-bc33-7870d4f3adc5")); //Gives the npc my troll skin
npc.spawn(player.getLocation()); //Spawns at server spawn
```

Result:
![Result](http://i.teg.pw/g3ri8.png)

There was one time where it actually worked, but hasn't worked since then.

**Comment by Techcable** [comment]
Are you on 1.7.9?

**Comment by tavonkelly** [comment]
Yea, the protocol hack version of Spigot

**Comment by Techcable** [comment]
1.7.9 and protocol hack?

**Comment by tavonkelly** [comment]
Yea

**Comment by Techcable** [comment]
Can you update to 1.7.10 protocol hack?
1.7.9 protocol hack is unsupported
