### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid UUID string:

### ISSUE THREAD

**Issue by legostarwarszach** [TechzoneMC/NPCLib#4]
Full StackTrace:
http://pastebin.com/g0xFYSTQ

Code: 
http://pastebin.com/SMT515G8
(ZAF.java:62 is: npc.setSkin("Legostarwarszach");)

**Comment by legostarwarszach** [comment]
In your ProfileUtils class, on line 175 (return UUID.fromString(raw);), 
I think you meant: return UUID.fromString(dashed);
That should fix the problem

**Comment by Techcable** [comment]
Yes it should, thanks for the info.
I only use skin uuids in my plugin :).
