### ISSUE TITLE
Weird bodies

### ISSUE THREAD

**Issue by Teg-MC** [TechzoneMC/NPCLib#7]
The body of an NPC doesn't change based of the yaw of the location/head which results in this:

![](http://i.teg.pw/7n312.png)

Also after what seems to be a random out of time, the head and body turns to the correct pitch and yaw what was set intentionally. Though this only happens when I teleport the NPC to the location I spawn it, right after I spawn it

**Comment by Techcable** [comment]
Have you tried npclib 2.0?

**Comment by Techcable** [comment]
Try the latest build i do setPositionRotaiton() there.

**Comment by tavonkelly** [comment]
Latest build works. Thanks

**Comment by Techcable** [comment]
:smile_cat:
